### PR TITLE
[release-4.12] OCPBUGS-15251: Add support for protocolStrategy API field to enable force_tcp configuration

### PR DESCRIPTION
**Pull request by gcs278**
This is a manual cherry-pick of https://github.com/openshift/cluster-dns-operator/pull/359 because the API (https://github.com/openshift/api/pull/1500) is also being backported as https://github.com/openshift/api/pull/1502 and needed to be manually vendored.

`go.mod`: Vendor API support for protocolStrategy
`pkg/operator/controller/controller_dns_configmap.go`: Logic to add force_tcp in corefile if protocolStrategy is TCP
`pkg/operator/controller/controller_dns_configmap_test.go`: Unit tests `pkg/operator/controller/testdata/*`: New corefiles for unit testing

### CODE REVIEW

**Comment by candita** [comment]
Pulling in @frobware or @knobunc.  I'm not sure how to review the backport of vendored openshift/api go modules for this bug fix.  What is being backported seems like much more than what is needed by this bug fix.  Is that anything to worry about?

**Comment by Miciah** [comment]
/approve
/lgtm

This is a low-risk change that adds and implements a new API field in the operator DNS config. This new field defaults to empty and has no effect unless the cluster-admin specifies a nonempty value for it.  

The one difference that catches my attention vis-à-vis the release-4.13 backport PR, #372, and this PR is that bumping openshift/api brings in a lot of reformatting of the descriptions in the CRD, but these changes are all cosmetic, and possibly improvements.  I'm curious whether this PR improves the output of the numbered list in the `oc explain DNS.spec.upstreamResolvers.transportConfig.tls.caBundle --api-version=operator.openshift.io/v1` output, for example.  Anyway, the formatting changes should not affect functionality.  
/label backport-risk-assessed

**Comment by Miciah** [comment]
> Pulling in @frobware or @knobunc. I'm not sure how to review the backport of vendored openshift/api go modules for this bug fix. The vendored openshift/api code being backported seems like much more than what is needed by this bug fix. Is that anything to worry about?

Repeating from internal discussion for transparency:  The large number of changes result from the infrequent openshift/api bumps in cluster-dns-operator's release-4.12 branch, and most of the changes have no impact on cluster-dns-operator.  For example, this operator does not use the IngressController API or instantiate its CRD, and so the changes to `vendor/github.com/openshift/api/operator/v1/types_ingress.go` that come with bumping openshift/api in cluster-dns-operator do not have any impact.

**Pull request merged**
