### PR TITLE
Bug 1690342: Update Progressing condition if upgrade happened

### PR DESCRIPTION
**Pull request by Miciah**
* `pkg/operator/controller/status.go`:
* `pkg/operator/controller/status_test.go` (`syncOperatorStatus`): Pass old versions to `computeOperatorStatusConditions`.
(`computeOperatorStatusConditions`): Pass old versions to `computeOperatorProgressingCondition`.
(`computeOperatorProgressingCondition`): Add "Upgraded x to y" message if old and current versions of an image do not match.
(`TestComputeOperatorStatusConditions`): Add test cases.

### CODE REVIEW

**Comment by danehans** [comment]
@Miciah it's interesting that the ingress operator does not need this fix: https://bugzilla.redhat.com/show_bug.cgi?id=1690333

**Comment by Miciah** [comment]
> @Miciah it's interesting that the ingress operator does not need this fix: https://bugzilla.redhat.com/show_bug.cgi?id=1690333

Also, https://bugzilla.redhat.com/show_bug.cgi?id=1695210.  I'm not entirely confident that the problem does not still exist in the ingress operator; it may only be more difficult to trigger.

**Comment by Miciah** [comment]
Note that in both https://bugzilla.redhat.com/show_bug.cgi?id=1690333#c6 and https://bugzilla.redhat.com/show_bug.cgi?id=1695210#c2, the available condition changes, which means that at some point, not all ingress controllers are available, and that is sufficient to cause the progressing condition to change.  If an upgrade happens without causing ingress controllers to become unavailable, then the ingress operator may fail to update the progressing condition.

**Pull request merged**
