### PR TITLE
DPP-10859: Update Bugzilla links to "Networking" component

### PR DESCRIPTION
**Pull request by Miciah**
Update Bugzilla links that reference the "DNS" component to instead use the "Networking" component and "DNS" subcomponent.

* `.github/ISSUE_TEMPLATE/config.yml`:
* `README.md`: Update Bugzilla links.

### CODE REVIEW

**Comment by lihongan** [comment]
https://github.com/openshift/cluster-dns-operator/pull/333

**Comment by Miciah** [comment]
We discussed it, and engineering may unilaterally approve PRs that only change README files and GitHub configuration.
/approve
/label docs-approved
/label px-approved

**Pull request merged**
