### PR TITLE
Publish operator status

### PR DESCRIPTION
**Pull request by Miciah**
#### Add openshift/cluster-version-operator dependency

* `Gopkg.lock`:
* `Gopkg.toml`:
* `vendor/github.com/openshift/cluster-version-operator`: Import package in order to have the necessary API types for updating operator status.

#### Publish operator status

Create (if necessary) and update a ClusterOperator object to indicate the operator's status.

* `cmd/cluster-dns-operator/main.go`: Add a watch on daemonsets in the application namespace to trigger reconciliation on status updates.
* `manifests/0000_08_cluster-dns-operator_00-cluster-role.yaml`: Allow the operator to create, get, and update clusteroperators.
* `pkg/manifests/bindata.go`: Regenerate.
* `pkg/util/clusteroperator/status.go`: Add new functions: `SetStatusCondition` and `ConditionsEqual`.
* `pkg/util/clusteroperator/status_test.go`: Add tests.
* `pkg/stub/status.go`: Add new functions: `syncOperatorStatus`, `getOperatorState`, and `computeStatusConditions`.
Use `getOperatorState` in `syncOperatorStatus` to get the prerequisite state for computing the operator's status.
Use `computeStatusConditions` in `syncOperatorStatus` to compute the status.
Use `clusteroperator.ConditionsEqual` in `syncOperatorStatus` to determine whether an update is needed.
Use `clusteroperator.SetStatusCondition` in `computeStatusConditions` to compute new conditions.
* `pkg/stub/handler.go`: Use `syncOperatorStatus` in `Handle` to update ClusterOperator.
* `pkg/stub/handler_test.go`: Add tests.

### CODE REVIEW

**Comment by ironcladlou** [comment]
This looks good; let me know when you're satisfied with manual testing (using a custom build image, etc.).

**Comment by Miciah** [comment]
Latest push changes `syncOperatorStatus` to update the status subresource, as necessitated by https://github.com/openshift/cluster-version-operator/pull/47.

Tested using `FOCUS='DNS' SKIP='\[Disabled:.+\]|\[Disruptive\]|\[Skipped\]|\[Slow\]|\[Flaky\]|\[local\]|\[Local\]' TEST_ONLY=1 test/extended/conformance.sh`:

    [Fail] DNS [It] should answer endpoint and wildcard queries for the cluster [Conformance] 
    [Suite:openshift/conformance/parallel/minimal]
    /home/mmasters/go/src/github.com/openshift/origin/test/extended/dns/dns.go:231
    
    Ran 6 of 1250 Specs in 99.796 seconds
    FAIL! -- 5 Passed | 1 Failed | 0 Pending | 1244 Skipped

The wildcard test is expected to fail at this time.

**Comment by Miciah** [comment]
/hold

Touching up RBAC.

**Comment by Miciah** [comment]
Latest push changes RBAC to allow updates to the clusteroperator's status subresource.  I tested again and got the same results.

**Pull request merged**
