### PR TITLE
Bug 1707062: Set terminationMessagePolicy=FallbackToLogsOnError for DNS operator and operands

### PR DESCRIPTION
**Pull request by pravisankar**
- FallbackToLogsOnError termination message policy will tell k8s to use the
last chunk of container log output if the termination message file is empty
and the container exited with an error.

More details: https://kubernetes.io/docs/tasks/debug-application-cluster/determine-reason-pod-failure/

### CODE REVIEW

**Comment by Miciah** [comment]
/lgtm
/hold
Holding for 4.2.

**Comment by smarterclayton** [comment]
I'd like to see this in 4.1.z post GA

/cherrypick release-4.1

**Pull request merged**
