### PR TITLE
Bug 1905323: Request appropriate memory for dns-node-resolver container

### PR DESCRIPTION
**Pull request by rfredette**
Cluster components are expected to request cpu & memory resources. dns-node-resolver already requested an amount of cpu time, but didn't include a memory request.

Following the guidelines [here](https://github.com/openshift/enhancements/blob/master/CONVENTIONS.md#resources-and-limits), I ran `make test-e2e` against a cluster on AWS running a 4.7 nightly build. I queried prometheus for the metric `container_memory_usage_bytes{container="dns-node-resolver"}` every 15 seconds between the start and finish of the e2e run, then I sorted the data points by memory usage to find the 90th percentile.

I'm not sure why, but there was a spread of about 13MiB of memory used between different dns-node-resolver containers in the daemonset. Looking at all the containers as a single set, the 90th percentile memory usage was 11,239,424 bytes, but one of the individual containers had a 90th percentile memory usage of 19,963,904 bytes, or about 19MiB. I chose to use the 90th percentile number from the individual container.

Adding 10% overhead to that number produced 20.94MiB, which I rounded to 21MiB.

### CODE REVIEW

**Comment by lihongan** [comment]
@rfredette seems the dns-operator container also didn't include a memory request.
```
# oc -n openshift-dns-operator get deployment/dns-operator -oyaml
<---snip--->
        name: dns-operator
        resources:
          requests:
            cpu: 10m
```
could you have a double check?

**Comment by rfredette** [comment]
@lihongan you are correct, dns-operator is missing a memory request. I'll add that to this PR today.

**Comment by sgreene570** [comment]
@rfredette https://github.com/openshift/cluster-dns-operator/pull/226 will resolve the failures seen on e2e-aws-operator.

**Comment by Miciah** [comment]
/test e2e-aws-operator
now that #226 has merged.

**Comment by Miciah** [comment]
/lgtm
Thanks!

**Pull request merged**
