### PR TITLE
Bug 1884053: Configure CoreDNS to shut down gracefully

### PR DESCRIPTION
**Pull request by Miciah**
#### Configure CoreDNS to shut down gracefully

This PR is the same as #205, which was reverted with #213, except that this PR does not change DNS pods' termination grace period.

Note that this change does not by itself solve [BZ#1884053](http://bugzilla.redhat.com/show_bug.cgi?id=1884053).  We still need the graceful node shutdown feature referenced in the BZ to get correct draining behavior on shutdown.  However, this change should reduce glitches when the pod comes back up after a node reboot.  

* `assets/dns/daemonset.yaml`: Change the readiness probe to use `:8181/ready`.
* `pkg/manifests/bindata.go`: Regenerate.
* `pkg/operator/controller/controller_dns_configmap.go` (`corefileTemplate`): Configure CoreDNS's health plugin to sleep 20 seconds when CoreDNS is shut down.  Enable CoreDNS's ready plugin in order to provide a readiness endpoint on `:8181/ready`, which doesn't report ready until all plugins are initialized and stops reporting ready when CoreDNS is shutting down.
* `pkg/operator/controller/controller_dns_configmap_test.go` (`TestDesiredDNSConfigmap`): Adjust for changes to `corefileTemplate`.

#### Delete `TestCoreDNSImageUpgrade`

Delete the `TestCoreDNSImageUpgrade` CI test.  This test is unreliable, and we can achieve sufficient test coverage without it.

* `test/e2e/operator_test.go` (`TestCoreDNSImageUpgrade`, `setVersion`, `setImage`,`checkCurrentDNSImage`): Delete functions.

#### Add `TestCoreDNSDaemonSetReconciliation`

Add an end-to-end test that verifies that the operator reconciles changes to the dns-default daemonset.  This new test adds a node selector to the daemonset and verifies that the operator reverts the change.

The operator already has unit tests to verify that the daemonset update logic handles changes to image pullspecs and other important fields. Together, the new end-to-end test and the existing unit tests should provide sufficient test coverage for reconciliation of daemonsets.

* `test/e2e/operator_test.go` (`TestCoreDNSDaemonSetReconciliation`): New test.  Verify that the operator reconciles the dns-default daemonset.

### CODE REVIEW

**Comment by sgreene570** [comment]
Timed out on `TestCoreDNSImageUpgrade`
/test e2e-aws-operator

**Comment by Miciah** [comment]
Seeing the same familiar flakes, and no evidence of DNS problems.
/retest

**Comment by sgreene570** [comment]
Timed out on `TestCoreDNSImageUpgrade` again. Maybe the changes here require a timeout bump for that test, which would make sense?

**Comment by Miciah** [comment]
Rebased.

**Comment by sgreene570** [comment]
e2e operator is passing and this PR has been properly rebased. Looks good! 
/lgtm

**Pull request merged**
