### PR TITLE
Bug 1950270: go.mod: Update openshift/api & go version

### PR DESCRIPTION
**Pull request by sgreene570**
**go.mod: Update openshift/api & go version**

go.*:

Update openshift/api to commit `c22782737ea0a882ed8d4e2c9bd3b974ee3bfca0`
to pull in https://github.com/openshift/api#886.
Bump to go version 1.16 in go.mod. Run `go mod tidy`.
Note that the DNS operator switched to go 1.16 for CI builds in #249.

vendor:

Run `go mod vendor`.

**manifests: Update generated CRD** 

manifests/0000_70_dns-operator_00-custom-resource-definition.yaml:

Run `make update` and commit the changes to the DNS operator CRD.

This commit resolves Bug 1950270, in which
`oc explain dns.spec.nodePlacement --api-version=operator.openshift.io/v1`
displays an outdated default node selector.

### CODE REVIEW

**Comment by sgreene570** [comment]
rebased

**Comment by sgreene570** [comment]
rebased 
https://github.com/openshift/release/pull/18083 has merged
/unhold

**Comment by sgreene570** [comment]
Verify job is now passing! 
:partying_face:

**Comment by Miciah** [comment]
> Update openshift/api to commit `c22782737ea0a882ed8d4e2c9bd3b974ee3bfca0`
> to pull in https://github.com/openshift/api#886.

Link should be https://github.com/openshift/api/pull/886.  Otherwise looks good.  Thanks!

/lgtm

**Comment by Miciah** [comment]
Thanks!
/lgtm

**Pull request merged**
