### PR TITLE
Bug 1778529: Revert "Integrate operator metrics with Prometheus"

### PR DESCRIPTION
**Pull request by Miciah**
This reverts #122.

### CODE REVIEW

**Comment by ironcladlou** [comment]
/hold

I don't think this is the problem yet.

**Comment by ironcladlou** [comment]
I think metrics issues were a red herring (see https://bugzilla.redhat.com/show_bug.cgi?id=1778529#c1). Let's keep this change once https://github.com/openshift/cluster-dns-operator/pull/144 is proven to be effective.

**Comment by frobware** [comment]
> I think metrics issues were a red herring (see https://bugzilla.redhat.com/show_bug.cgi?id=1778529#c1). Let's keep this change once #144 is proven to be effective.

Should we close this now? Is this PR still pertinent?

**Comment by ironcladlou** [comment]
Closing due to age — reopen if I've made a mistake.

/close

**Pull request closed without merging**
