### PR TITLE
Bug 1919737: Set CoreDNS readiness probe period and timeout each to 3 seconds

### PR DESCRIPTION
**Pull request by Miciah**
#### Set CoreDNS readiness probe period and timeout to 3 seconds

Change the readiness probe for CoreDNS from using a 10-second period and timeout to using a 3-second period and timeout in order to reduce the time to remove the endpoint if CoreDNS becomes unresponsive.

* `assets/dns/daemonset.yaml`: Set readiness probe period and timeout to 3 seconds.
* `pkg/manifests/bindata.go`: Regenerate.

#### Reconcile all readiness probe parameters

Check all parameters of the CoreDNS daemonset's readiness probe, and update the daemonset if any of the probe's parameters differ from the expected values.

Before this commit, the DNS controller only reconciled the readiness probe's handler and ignored changes to other parameters of the probe.

* `pkg/operator/controller/controller_dns_daemonset.go` (`daemonsetConfigChanged`): Check if any of the readiness probe's parameters changed and update them if they did.
* `pkg/operator/controller/controller_dns_daemonset_test.go` (`TestDaemonsetConfigChanged`): Add test case to verify that `daemonsetConfigChanged` detects changes to the readiness probe's `periodSeconds` parameter.

### CODE REVIEW

**Comment by knobunc** [comment]
I like this.  I'd lgtm, but want other people to consider too.

**Comment by Miciah** [comment]
I see some lookup failures in [the last e2e-upgrade CI job run](https://prow.ci.openshift.org/view/gs/origin-ci-test/pr-logs/pull/openshift_cluster-dns-operator/234/pull-ci-openshift-cluster-dns-operator-master-e2e-upgrade/1359706555318013952), and [`pods.json`](https://gcsweb-ci.apps.ci.l2s4.p1.openshiftapps.com/gcs/origin-ci-test/pr-logs/pull/openshift_cluster-dns-operator/234/pull-ci-openshift-cluster-dns-operator-master-e2e-upgrade/1359706555318013952/artifacts/e2e-upgrade/gather-extra/artifacts/pods.json) shows that one of the DNS pods was oom-killed.  However, several other pods also report having been oom-killed, so DNS may have been a victim and not a culprit here.  
/test e2e-upgrade

Meanwhile, must-gather failed on [the last e2e-aws CI job run](https://prow.ci.openshift.org/view/gs/origin-ci-test/pr-logs/pull/openshift_cluster-dns-operator/234/pull-ci-openshift-cluster-dns-operator-master-e2e-aws/1359706555250905088) because DNS wasn't working, which is concerning.  Must-gather is known to be flaky, but the DNS failures are concerning, so let's keep an eye on that.
/test e2e-aws

**Comment by Miciah** [comment]
e2e-upgrade passed, and e2e-aws failed with errors related to sandbox initialization and nothing obviously related to DNS.
/test e2e-aws

**Comment by sgreene570** [comment]
/lgtm
looks good.

**Pull request merged**
