### PR TITLE
[release-4.8] Bug 1974978: status: Watch daemonsets

### PR DESCRIPTION
**Pull request by Miciah**
This is a manual cherry-pick of #283.  I am creating the PR manually so that it can be tested in parallel to #283.

### CODE REVIEW

**Comment by sgreene570** [comment]
Interesting, SNO jobs are required to pass to merge to release-4.8?

/lgtm

**Comment by frobware** [comment]
Alerts shouldn't report any alerts in firing or pending state apart from Watchdog and AlertmanagerReceiversNotConfigured

/retest

**Comment by Miciah** [comment]
/hold
CI is blocked on https://bugzilla.redhat.com/show_bug.cgi?id=1977479.

**Comment by bparees** [comment]
the single node failures should clear up once openshift/operator-framework-olm#108 merges

**Comment by bparees** [comment]
the failure in the aws-single-node job is consistent and tied to olm(known issue), not this PR.  overriding.

/override ci/prow/e2e-aws-single-node

**Pull request merged**
