### PR TITLE
Add management workload annotations

### PR DESCRIPTION
**Pull request by cynepco3hahue**
In support of the workload partitioning feature
(openshift/enhancements#703), we need to add
annotations to all management pods and namespaces so they can be
properly identified and assigned to segregated management cores on
clusters configured to do so.

Signed-off-by: Artyom Lukianov <alukiano@redhat.com>

### CODE REVIEW

**Comment by Miciah** [comment]
Do we need to update the deployment, daemonset, and namespaces if they already exist?  That is, are these annotations needed on upgraded clusters, or are they only needed on newly launched 4.8 clusters?

**Comment by imiller0** [comment]
> Do we need to update the deployment, daemonset, and namespaces if they already exist? That is, are these annotations needed on upgraded clusters, or are they only needed on newly launched 4.8 clusters?

The initial target of this work is for single-node-openshift clusters which are also new in 4.8. No upgrade path is needed right now.

**Comment by Miciah** [comment]
/lgtm
@cynepco3hahue, do you have an exception to get this merged in 4.8, or an associated BZ?

**Comment by cynepco3hahue** [comment]
I know that @browsell asked for an exception. @browsell Any updates regarding the exception.

**Comment by Miciah** [comment]
Looks like you need to rebase and run `make update` now that https://github.com/openshift/cluster-dns-operator/pull/215 has merged.

**Comment by Miciah** [comment]
/hold
Please run `make update`.

**Pull request merged**
