### PR TITLE
Bug 1687976: Allow update of node resolver image

### PR DESCRIPTION
**Pull request by pravisankar**

### CODE REVIEW

**Comment by ironcladlou** [comment]
Awesome, thanks!
/lgtm

**Comment by Miciah** [comment]
/lgtm

    level=error msg="\t* module.vpc.aws_route_table_association.route_net[0]: 1 error occurred:"
    level=error msg="\t* aws_route_table_association.route_net.0: timeout while waiting for state to become 'success' (timeout: 5m0s)"

/test e2e-aws

**Pull request merged**
