### PR TITLE
Bug 1915473: Annotate manifests for single-node-developer cluster profile

### PR DESCRIPTION
**Pull request by cfergeau**
This partially implements phase 1 of https://github.com/openshift/enhancements#482
and does not change behavior. Initially, all cluster-dns-operator CRD
manifests are included in the single-node-developer cluster profile.
Follow-on PRs may exclude any of these that are not needed in the
profile.

### CODE REVIEW

**Comment by cfergeau** [comment]
Could this get a review?

**Comment by cfergeau** [comment]
@danehans @candita could you take a look?

**Comment by cfergeau** [comment]
How can I get a review on this? @Miciah @sgreene570 ?

**Comment by praveenkumar** [comment]
Can some look into this with higher priority because it is breaking the CI in cluster is provision with `single-node-developer` profile as this operator is excluded and there is no dns for cluster.

**Comment by sgreene570** [comment]
Sorry for the delay!
/lgtm

**Pull request merged**
