### PR TITLE
Bump for controller-runtime v0.9.0

### PR DESCRIPTION
**Pull request by alebedev87**

### CODE REVIEW

**Comment by alebedev87** [comment]
/retest
reason: "failed to acquire lease for "aws-quota-slice": resources not found"

**Comment by sgreene570** [comment]
e2e-aws-operator  has passed and sample logs in https://gcsweb-ci.apps.ci.l2s4.p1.openshiftapps.com/gcs/origin-ci-test/pr-logs/pull/openshift_cluster-dns-operator/282/pull-ci-openshift-cluster-dns-operator-master-e2e-aws-operator/1406950983522586624/artifacts/e2e-aws-operator/gather-extra/artifacts/pods/openshift-dns-operator_dns-operator-74bbfc6f7-6gzv5_dns-operator.log appear normal

Thanks!
/lgtm

**Comment by alebedev87** [comment]
/retest
reason: "ailed to create cluster: failed to apply Terraform: failed to complete the change"

**Pull request merged**
