### PR TITLE
OCPBUGS-13965: Bump vendors k8s libraries to 0.27.2

### PR DESCRIPTION
**Pull request by gcs278**
Bump openshift-api, client-go, controller-runtime, kubectl for k8s 0.27.2. Need to bump Controller-runtime to v0.15.0 because it is a dependency of client-go v0.27.2.

```
go get github.com/openshift/api@8bbcb7ca71836dc87cce3ef63647403dc9d0fbea
go get k8s.io/client-go@v0.27.2
go get sigs.k8s.io/controller-runtime@v0.15.0
go get k8s.io/kubectl@v0.27.2
go mod tidy
go mod vendor
```

`pkg/operator/client/client.go`,
`pkg/operator/controller/controller.go`,
`pkg/operator/controller/status/controller.go`:  Updates for source.Kind conversion from type to function, MapFunc definition update to add context argument, handler.EnqueueRequestForOwner definition update for scheme and mapper.
`pkg/operator/operator.go`: Removed deprecated MultiNamespacedCacheBuilder for cache.Options{}. Added override to client.Options.Cache in NewClient function so client won't use cache. Removed deprecated Namespace manager.Options{} field.

### CODE REVIEW

**Comment by gcs278** [comment]
I found https://github.com/openshift/machine-api-operator/blob/master/go.mod which uses an alpha release version of controller-runtime: `sigs.k8s.io/controller-runtime v0.15.0-alpha.0.0.20230509061743-4d3244f28eef`
Will attempt to use this for now.

**Comment by gcs278** [comment]
/unhold
controller-runtime has released v0.15

**Comment by ShudiLi** [comment]
From QE side, tested it with 4.13.0-0.ci.test-2023-05-24-010829-ci-ln-iwq70g2-latest, see all the changes except "	github.com/stretchr/testify v1.8.1"

1.
% oc get clusterversion
NAME      VERSION                                                   AVAILABLE   PROGRESSING   SINCE   STATUS
version   4.13.0-0.ci.test-2023-05-24-010829-ci-ln-iwq70g2-latest   True        False         23m     Cluster version is 4.13.0-0.ci.test-2023-05-24-010829-ci-ln-iwq70g2-latest
%

2.
%oc -n openshift-dns-operator rsync dns-operator-7f7d76974f-qx7lp:/usr/bin/dns-operator .
% go version -m dns-operator                        
dns-operator: go1.20.3
	path	github.com/openshift/cluster-dns-operator/cmd/dns-operator
	mod	github.com/openshift/cluster-dns-operator	(devel)	
	dep	github.com/apparentlymart/go-cidr	v1.0.0	
	dep	github.com/beorn7/perks	v1.0.1	
	dep	github.com/cespare/xxhash/v2	v2.2.0	
	dep	github.com/davecgh/go-spew	v1.1.1	
	dep	github.com/emicklei/go-restful/v3	v3.9.0	
	dep	github.com/evanphx/json-patch/v5	v5.6.0	
	dep	github.com/fsnotify/fsnotify	v1.6.0	
	dep	github.com/go-logr/logr	v1.2.4	
	dep	github.com/go-openapi/jsonpointer	v0.19.6	
	dep	github.com/go-openapi/jsonreference	v0.20.1	
	dep	github.com/go-openapi/swag	v0.22.3	
	dep	github.com/gogo/protobuf	v1.3.2	
	dep	github.com/golang/groupcache	v0.0.0-20210331224755-41bb18bfe9da	
	dep	github.com/golang/protobuf	v1.5.3	
	dep	github.com/google/gnostic	v0.5.7-v3refs	
	dep	github.com/google/go-cmp	v0.5.9	
	dep	github.com/google/gofuzz	v1.2.0	
	dep	github.com/google/uuid	v1.3.0	
	dep	github.com/imdario/mergo	v0.3.12	
	dep	github.com/josharian/intern	v1.0.0	
	dep	github.com/json-iterator/go	v1.1.12	
	dep	github.com/mailru/easyjson	v0.7.7	
	dep	github.com/matttproud/golang_protobuf_extensions	v1.0.4	
	dep	github.com/modern-go/concurrent	v0.0.0-20180306012644-bacd9c7ef1dd	
	dep	github.com/modern-go/reflect2	v1.0.2	
	dep	github.com/munnerz/goautoneg	v0.0.0-20191010083416-a7dc8b61c822	
	dep	github.com/openshift/api	v0.0.0-20230503133300-8bbcb7ca7183	
	dep	github.com/pkg/errors	v0.9.1	
	dep	github.com/prometheus/client_golang	v1.15.1	
	dep	github.com/prometheus/client_model	v0.4.0	
	dep	github.com/prometheus/common	v0.42.0	
	dep	github.com/prometheus/procfs	v0.9.0	
	dep	github.com/sirupsen/logrus	v1.9.0	
	dep	github.com/spf13/pflag	v1.0.5	
	dep	golang.org/x/net	v0.10.0	
	dep	golang.org/x/oauth2	v0.5.0	
	dep	golang.org/x/sys	v0.8.0	
	dep	golang.org/x/term	v0.8.0	
	dep	golang.org/x/text	v0.9.0	
	dep	golang.org/x/time	v0.3.0	
	dep	gomodules.xyz/jsonpatch/v2	v2.3.0	
	dep	google.golang.org/protobuf	v1.30.0	
	dep	gopkg.in/inf.v0	v0.9.1	
	dep	gopkg.in/yaml.v2	v2.4.0	
	dep	gopkg.in/yaml.v3	v3.0.1	
	dep	k8s.io/api	v0.27.2	
	dep	k8s.io/apimachinery	v0.27.2	
	dep	k8s.io/client-go	v0.27.2	
	dep	k8s.io/component-base	v0.27.2	
	dep	k8s.io/klog/v2	v2.90.1	
	dep	k8s.io/kube-openapi	v0.0.0-20230501164219-8b0f38b5fd1f	
	dep	k8s.io/kubectl	v0.27.2	
	dep	k8s.io/utils	v0.0.0-20230209194617-a36077c30491	
	dep	sigs.k8s.io/controller-runtime	v0.15.0	
	dep	sigs.k8s.io/json	v0.0.0-20221116044647-bc3834ca7abd	
	dep	sigs.k8s.io/structured-merge-diff/v4	v4.2.3	
	dep	sigs.k8s.io/yaml	v1.3.0	
	build	-buildmode=exe
	build	-compiler=gc
	build	CGO_ENABLED=0
	build	GOARCH=amd64
	build	GOOS=linux
	build	GOAMD64=v1
	build	vcs=git
	build	vcs.revision=f3272515c4ded285178670d8d6e045843436848c
	build	vcs.time=2023-05-05T15:53:14Z
	build	vcs.modified=true
% 

3. can't see "github.com/stretchr/testify v1.8.1"
% go version -m dns-operator | grep github.com/stretchr/testify
%

**Comment by ShudiLi** [comment]
/label qe-approved
thanks

**Comment by gcs278** [comment]
/hold
`MultiNamespacedCacheBuilder` has been deprecated. I feel like I should address new deprecations in this bump.

**Comment by gcs278** [comment]
/unhold
Removed call to deprecated `MultiNamespacedCacheBuilder` and fixed client using cache when we are intended to keep them separate.

**Pull request merged**
