### PR TITLE
 Changed delete handling to use garbage collection

### PR DESCRIPTION
**Pull request by pravisankar**
- ClusterDNS specific resources are tied to its daemonset as owner ref
so that deletion of this daemonset will trigger deletion of corresponding
configmap and service resources.

### CODE REVIEW

**Comment by pravisankar** [comment]
@openshift/sig-network-edge PTAL

**Comment by Miciah** [comment]
The `sdk.Create` has the following doctext:

    // Create creates the provided object on the server and updates the arg
    // "object" with the result from the server(UID, resourceVersion, etc).

So `getDaemonSetOwnerRef` should be able to use `ds.UID` directly, with no need for the `d` variable or `sdk.Get` call.

**Comment by pravisankar** [comment]
@openshift/sig-network-edge @Miciah  updated, PTAL

**Comment by ironcladlou** [comment]
I don't think deletes will work when managed by CVO (we don't grant `delete` for DaemonSet yet), but I think it's okay for now since we only care about create at the moment for getting our stuff integrated. I mention this as another example to consider for our e2e tests.

/lgtm

**Pull request merged**
