### PR TITLE
OCPBUGS-24602: Enable topology-aware hints iff nodes in >=2 zones

### PR DESCRIPTION
**Pull request by Miciah**
Only set the `service.kubernetes.io/topology-aware-hints` annotation on the DNS service if the cluster has valid nodes in at least two different topology zones.

Without this change, a cluster in which all nodes had the same `topology.kubernetes.io/zone` label value would emit "TopologyAwareHintsDisabled" events repeatedly.

Follow-up to #364..

* `pkg/operator/controller/controller_dns_service.go` (`shouldEnableTopologyAwareHints`): Check that the number of zones (not just nodes) is >= 2.
* `pkg/operator/controller/controller_dns_service_test.go` (`Test_shouldEnableTopologyAwareHints`): Amend test cases to include multiple zones.

### CODE REVIEW

**Comment by Miciah** [comment]
[e2e-aws-ovn-operator passed](https://prow.ci.openshift.org/view/gs/origin-ci-test/pr-logs/pull/openshift_cluster-dns-operator/398/pull-ci-openshift-cluster-dns-operator-master-e2e-aws-ovn-operator/1734313589285588992), [`nodes.json`](https://gcsweb-ci.apps.ci.l2s4.p1.openshiftapps.com/gcs/origin-ci-test/pr-logs/pull/openshift_cluster-dns-operator/398/pull-ci-openshift-cluster-dns-operator-master-e2e-aws-ovn-operator/1734313589285588992/artifacts/e2e-aws-ovn-operator/gather-extra/artifacts/nodes.json) from the job's gather-extra artifacts shows nodes in 2 zones, and [`services.json`](https://gcsweb-ci.apps.ci.l2s4.p1.openshiftapps.com/gcs/origin-ci-test/pr-logs/pull/openshift_cluster-dns-operator/398/pull-ci-openshift-cluster-dns-operator-master-e2e-aws-ovn-operator/1734313589285588992/artifacts/e2e-aws-ovn-operator/gather-extra/artifacts/services.json) shows that the "dns-default" still has the `"service.kubernetes.io/topology-aware-hints": "auto"` annotation.  @mandre tested on OpenStack, where all the nodes are in a single zone, and observed that cluster-dns-operator was healthy and did **not** set the annotation on the service.  These results indicate that the change in this PR has the intended effect.

**Review by mandre — COMMENTED** [review]
Thanks for the fix @Miciah, I confirm this indeed resolves the issue I reported in https://issues.redhat.com/browse/OCPBUGS-24602.

LGTM.

/retest-required

**Pull request merged**
