### PR TITLE
NE-1268: Replace bindata using embed

### PR DESCRIPTION
**Pull request by Miciah**
Replace go-bindata using the embed package added in Go 1.16.  This change simplifies the build process and reduces the likelihood of merge conflicts when PRs modify assets.

* `Makefile`: Delete `bindata` target.
* `go.mod`: Drop go-bindata.
* `go.sum`: Regenerate.
* `hack/update-generated-bindata.sh`: Delete file.
* `assets/`: Move from here...
* `pkg/manifests/assets/`: ...to here.  New directory.
* `pkg/manifests/bindata.go`: Delete file.
* `pkg/manifests/manifests.go` (`content`): New variable.  Store assets as an `embed.FS` value.
(`MustAsset`, `MustAssetString`): New functions.  Return assets using the new content variable.  These function definitions replace ones from the deleted `bindata.go` file.
* `tools/tools.go`: Delete go-bindata.
* `vendor/*`: Regenerate.

### CODE REVIEW

**Comment by Miciah** [comment]
[e2e-aws-ovn-serial failed](https://prow.ci.openshift.org/view/gs/origin-ci-test/pr-logs/pull/openshift_cluster-dns-operator/361/pull-ci-openshift-cluster-dns-operator-master-e2e-aws-ovn-serial/1643385801213480961) because the cluster was missing a control-plane node.  
/test e2e-aws-ovn-serial

**Comment by frobware** [comment]
```sh

% git log |head     
commit b5ddd77c936cd303db0a6048b7d3ac3b193cafc5
Author: Miciah Masters <miciah.masters@gmail.com>
Date:   Tue Apr 4 18:42:22 2023 -0400

    Replace bindata using embed
    
    Replace go-bindata using the embed package added in Go 1.16.  This change
    simplifies the build process and reduces the likelihood of merge conflicts
    when PRs modify assets.
    
[spicy] ~/src/github.com/openshift/cluster-dns-operator
% git clean -f -d -x

[spicy] ~/src/github.com/openshift/cluster-dns-operator
% rm -rf vendor

[spicy] ~/src/github.com/openshift/cluster-dns-operator
% ag bindata
hack/verify-generated-bindata.sh
13:OUTDIR="${TMP_DIR}" ./hack/update-generated-bindata.sh
15:diff -Naup {.,"${TMP_DIR}"}/pkg/manifests/bindata.go

```

I still see an outstanding reference to the old ways.

**Comment by Miciah** [comment]
> I still see an outstanding reference to the old ways.

https://github.com/openshift/cluster-dns-operator/compare/b5ddd77c936cd303db0a6048b7d3ac3b193cafc5..e95a82b4d45b6a77b879f56330be2b73ab1defe8 removes `hack/verify-generated-bindata.sh`,

**Comment by Miciah** [comment]
This is a build change that doesn't require docs, PX, or QE.
/label docs-approved
/label px-approved
/label qe-approved

**Comment by Miciah** [comment]
Rebased.

**Comment by Miciah** [comment]
[e2e-aws-ovn-serial failed](https://prow.ci.openshift.org/view/gs/origin-ci-test/pr-logs/pull/openshift_cluster-dns-operator/361/pull-ci-openshift-cluster-dns-operator-master-e2e-aws-ovn-serial/1684031572828753920) because `[Serial] [sig-auth][Feature:OAuthServer] [RequestHeaders] [IdP] test RequestHeaders IdP` failed:
```text
{  fail [github.com/openshift/origin/test/extended/oauth/requestheaders.go:218]: full response header: HTTP/1.1 403 Forbidden
Content-Length: 192
Audit-Id: fbb15e95-2538-4301-bcd4-cc7184bed6ba
Cache-Control: no-cache, no-store, max-age=0, must-revalidate
Content-Type: application/json
Date: Wed, 26 Jul 2023 04:16:56 GMT
Expires: 0
Pragma: no-cache
Referrer-Policy: strict-origin-when-cross-origin
X-Content-Type-Options: nosniff
X-Dns-Prefetch-Control: off
X-Frame-Options: DENY
X-Xss-Protection: 1; mode=block

{"kind":"Status","apiVersion":"v1","metadata":{},"status":"Failure","message":"forbidden: User \"system:anonymous\" cannot get path \"/metrics\"","reason":"Forbidden","details":{},"code":403}


Expected
    <string>: 403 Forbidden
to contain substring
    <string>: 401 Unauthorized
Ginkgo exit error 1: exit with code 1}
```
/test e2e-aws-ovn-serial

**Pull request merged**
