### PR TITLE
update to flat updatepayload structure

### PR DESCRIPTION
**Pull request by juanvallejo**
Updates Dockerfile to include a /manifests directory in image.

cc @deads2k @mfojtik @sttts

### CODE REVIEW

**Comment by ironcladlou** [comment]
Needs a corresponding fix for the integration test

**Comment by deads2k** [comment]
> Needs a corresponding fix for the integration test

What integration test?  Everything appears to be green.

**Comment by ironcladlou** [comment]
Gotta run them manually for now: https://github.com/openshift/cluster-dns-operator/blob/master/HACKING.md#tests

**Pull request merged**
