### PR TITLE
use GA kubelet OS label

### PR DESCRIPTION
**Pull request by rphillips**
ref: https://jira.coreos.com/browse/POD-114

### CODE REVIEW

**Comment by ironcladlou** [comment]
I see this passed upgrade tests — are the existing node labels getting migrated somehow?

/approve

**Comment by ironcladlou** [comment]
@Miciah @danehans PTAL

**Comment by Miciah** [comment]
> I see this passed upgrade tests — are the existing node labels getting migrated somehow?

No, we'll need to change `daemonsetConfigChanged` to update the daemonset if the node selector changes: https://github.com/openshift/cluster-dns-operator/blob/8f78ebaf88d60794af5bc407291b000691fac177/pkg/operator/controller/controller_dns_daemonset.go#L155

**Comment by ironcladlou** [comment]
>No, we'll need to change daemonsetConfigChanged to update the daemonset if the node selector changes:

Can you explain how the upgrade test is passing?

**Comment by Miciah** [comment]
> Can you explain how the upgrade test is passing?

I'll need to check, but I would guess that the test is not making sure that nothing continues to use the legacy label.

**Comment by Miciah** [comment]
But look at [daemonsets.json from e2e-aws-operator](https://storage.googleapis.com/origin-ci-test/pr-logs/pull/openshift_cluster-dns-operator/119/pull-ci-openshift-cluster-dns-operator-master-e2e-aws-upgrade/64/artifacts/e2e-aws-upgrade/daemonsets.json):

```json
        {
            "apiVersion": "extensions/v1beta1",
            "kind": "DaemonSet",
            "metadata": {
                "creationTimestamp": "2019-06-11T15:08:21Z",
                "generation": 2,
                "labels": {
                    "dns.operator.openshift.io/owning-dns": "default"
                },
                "name": "dns-default",
                "namespace": "openshift-dns",
                // ...
            },
            "spec": {
                // ...
                "template": {
                    // ...
                    "spec": {
                        // ...
                        "nodeSelector": {
                            "beta.kubernetes.io/os": "linux"
                        },
```

**Comment by rphillips** [comment]
The old and new labels are sticking around until kubernetes 1.17.

**Comment by Miciah** [comment]
> The old and new labels are sticking around until kubernetes 1.17.

We need a test to make sure that operators migrate the node selector now.  By the time we're testing upgrades to 1.17, we will be upgrading from clusters that started with operators that use the new label, and we could miss problems that only arise when upgrading long-lived clusters that started with operators from today or earlier.

**Comment by Miciah** [comment]
> > I see this passed upgrade tests — are the existing node labels getting migrated somehow?
> 
> No, we'll need to change `daemonsetConfigChanged` to update the daemonset if the node selector changes:
> 
> https://github.com/openshift/cluster-dns-operator/blob/8f78ebaf88d60794af5bc407291b000691fac177/pkg/operator/controller/controller_dns_daemonset.go#L155

https://github.com/openshift/cluster-dns-operator/pull/121 makes this change.

I still believe it would be prudent for e2e-aws-upgrade to make sure operators migrate to the new label.  Absent that, I suggest we merge #121 first, then rerun CI on this PR, and then manually verify that the operator has changed the daemonset to use the new node selector.

**Comment by rphillips** [comment]
rebased to rerun CI.

**Comment by Miciah** [comment]
CI run looks good, and the daemonset's node selector is correct at the end of the run:
```
% curl -s https://storage.googleapis.com/origin-ci-test/pr-logs/pull/openshift_cluster-dns-operator/119/pull-ci-openshift-cluster-dns-operator-master-e2e-aws-upgrade/70/artifacts/e2e-aws-upgrade/daemonsets.json | zcat | jq '.items|.[]|select(.metadata.name=="dns-default").spec.template.spec.nodeSelector'
{
  "kubernetes.io/os": "linux"
}
% 
```
/lgtm

**Pull request merged**
