### PR TITLE
Bug 2043787: Bump to Kubernetes 1.23 and Go 1.17

### PR DESCRIPTION
**Pull request by Miciah**
Bump to the latest openshift/api and k8s.io/api 1.23.  This requires bumping to controller-runtime 0.11.0 and Go 1.17 as well.

* `Dockerfile`: Bump to Go 1.17.
* `go.mod`: Bump openshift/api, k8s.io packages, and controller-runtime.
* `pkg/operator/controller/controller_dns_daemonset_test.go`: Adjust for a change in the k8s.io/api/core/v1 `Probe` type where an inlined field was renamed.
* `go.sum`:
* `vendor/*`: Regenerate.

### CODE REVIEW

**Comment by Miciah** [comment]
```
 level=error msg=Attempted to gather ClusterOperator status after installation failure: listing ClusterOperator objects: Get "https://api.ci-op-c1jqmj73-36945.origin-ci-int-aws.dev.rhcloud.com:6443/apis/config.openshift.io/v1/clusteroperators": dial tcp 18.210.60.56:6443: connect: connection refused 
```
/test e2e-aws-single-node

**Comment by Miciah** [comment]
```
Failing tests:

[Serial] [sig-auth][Feature:OAuthServer] [RequestHeaders] [IdP] test RequestHeaders IdP [Suite:openshift/conformance/serial]
```
/test e2e-aws-serial

**Comment by Miciah** [comment]
```
level=info msg=Creating infrastructure resources...
level=error
level=error msg=Error: Provider produced inconsistent result after apply
level=error
level=error msg=When applying changes to module.masters.aws_network_interface.master[2],
level=error msg=provider "openshift/local/aws" produced an unexpected new value: Root resource
level=error msg=was present, but now absent. 
```
/test e2e-aws-serial

**Comment by frobware** [comment]
I built, realised that failed because I was still using Go 1.16. Switched to Go 1.17, build is OK. Ran make test which was fine. Also adjusted my local copy to run the unit tests with the race detector enabled -- which pass too.

/skip
/lgtm

**Pull request merged**
